# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  password: <%= ENV['todo_DATABASE_PASSWORD'] %>


development:
  <<: *default
  database: todo_development

#  host: localhost
#  port: 5432
  #これのせいで失敗したFuck!

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV['todo_DATABASE_PASSWORD'] %>